.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/workflows/main.yaml, .releaserc, README.md, build/testScript.sh, configurationgovernancev1/configuration_governance_v1_integration_test.go, findingsv1/findings_v1_integration_test.go, notificationsv1/notifications_v1_integration_test.go
- GitHub action workflow added
- GitHub pull request template, bug report template, and feature request template added.
- ITs improved to run on GitHub actions.
- Some miscellaneous changes in various scripts to improve CI/CD jobs in GitHub actions.
=> fix(GitHubActions): migration from TravisCI

findingsv1/findings_v1.go, findingsv1/findings_v1_test.go
=> fix(SDK): regeneration after content-review

configurationgovernancev1/configuration_governance_v1.go, configurationgovernancev1/configuration_governance_v1_examples_test.go, configurationgovernancev1/configuration_governance_v1_integration_test.go, configurationgovernancev1/configuration_governance_v1_test.go
=> feat(Template API): Add support for Templates in Configuration API

README.md
=> feat(SDK): add support for posture management

.github/workflows/main.yaml, build/testScript.sh, posturemanagementv2/posture_management_v2.go, posturemanagementv2/posture_management_v2_examples_test.go, posturemanagementv2/posture_management_v2_integration_test.go, posturemanagementv2/posture_management_v2_suite_test.go, posturemanagementv2/posture_management_v2_test.go
Checks: https://github.com/IBM/scc-go-sdk/actions/runs/1514705004 ✅
=> fix('PostureManagement'): 'releasing v2 APIs'

posturemanagementv2/posture_management_v2_integration_test.go
=> Posturev2 it fix - timeout error

findingsv1/findings_v1.go
=> BREAKING CHANGE: releasing SDK without NotificationsAPI

.bumpversion.cfg
=> fix(CI): CI bumpversion fix

.bumpversion.cfg, README.md, v2/common/version.go
=> fix(CI): fixing release issue

v3/posturemanagementv2/posture_management_v2.go
=> added list of url for regions

v3/posturemanagementv2/posture_management_v2_integration_test.go
modified number to text enum for getProfile
=> modified number to text enum for getProfile

v3/posturemanagementv2/posture_management_v2.go, v3/posturemanagementv2/posture_management_v2_integration_test.go
=> test(posturemanagementv2): Integration tests Bug Fixes

v3/adminserviceapiv1/admin_service_api_v1.go, v3/adminserviceapiv1/admin_service_api_v1_examples_test.go, v3/adminserviceapiv1/admin_service_api_v1_integration_test.go, v3/adminserviceapiv1/admin_service_api_v1_suite_test.go, v3/adminserviceapiv1/admin_service_api_v1_test.go
Including some features  to the admin openapi into the sdk
=> feat(AdminAPI): Adding the notifications feature introduced Q4 2021

v3/posturemanagementv1/posture_management_v1.go
fix(PostureManagementAPI): Service URL to be picked according to selected region
=> fix(PostureManagementAPI): Service URL to be picked according to selected region

v3/posturemanagementv1/posture_management_v1.go, v3/posturemanagementv2/posture_management_v2.go, v3/posturemanagementv2/posture_management_v2_integration_test.go
fix(PostureManagementAPI): Modified IT cases as per functional changes made
=> fix(PostureManagementAPI): Modified IT cases as per functional changes made

v3/posturemanagementv2/posture_management_v2.go, v3/posturemanagementv2/posture_management_v2_examples_test.go, v3/posturemanagementv2/posture_management_v2_integration_test.go, v3/posturemanagementv2/posture_management_v2_suite_test.go, v3/posturemanagementv2/posture_management_v2_test.go
added new credential type and improved profile IT logic
=> added new credential type and improved profile IT

.github/workflows/main.yaml, v3/posturemanagementv2/posture_management_v2.go, v3/posturemanagementv2/posture_management_v2_examples_test.go, v3/posturemanagementv2/posture_management_v2_integration_test.go, v3/posturemanagementv2/posture_management_v2_suite_test.go, v3/posturemanagementv2/posture_management_v2_test.go
=> Posture cred type

.github/workflows/main.yaml, v3/go.mod, v3/go.sum, v3/posturemanagementv2/posture_management_v2.go
=> fix(go.mod): removed unused packages

v3/posturemanagementv2/posture_management_v2.go
fix(PostureManagementv2): "Service based service URL feature introduction (https://github.com/IBM/scc-go-sdk/issues/91)
=> fix(PostureManagementv2): "Service based service URL feature introduction (https://github.com/IBM/scc-go-sdk/issues/91)

v3/posturemanagementv2/posture_management_v2.go
=> fix(PostureManagementv2): "Service based service URL feature introduction (https://github.com/IBM/scc-go-sdk/issues/91)"

v4/posturemanagementv2/posture_management_v2.go, v4/posturemanagementv2/posture_management_v2_integration_test.go
task : https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3807
description : SCC - Posture Management - Include scheduling properties to Scan API
=> SCC-PM-task#3807- add scheduling parameters for scan

.github/workflows/main.yaml, CONTRIBUTING.md, build/testScript.sh
=> fix: using manual code to push gopages to gh-pages

.github/workflows/main.yaml
=> fix(Github Action): release phase

.github/workflows/main.yaml, .gitignore
https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
=> updated node version to 18 [skip ci]

.github/workflows/main.yaml, README.md, v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3_test.go
=> ci: fix the workflow triggers

CHANGELOG.md
=> docs: Changing the message for 5.0.1

v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3.go
- Adding SetInstanceID to the following:
- ReplaceCustomControlLibraryOptions
- ReplaceProfileOptions
- UpdateProviderTypeInstanceOptions
=> fix: Add func SetInstanceID to additional objects

v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3.go
This version adds various funcs of SetInstanceID to more objects:
- *ReplaceRuleOptions
- *UpdateProviderTypeInstanceOptions
=> fix: Adding the func SetInstanceID to various objects

CONTRIBUTING.md
* fix: Add profile_version in the ReplaceProfileOptions
* Adding the ProfileVersion field onto integration test
* Adding ListProviderTypes to include Instance path
* Requiring InstanceID to the ListProviderTypesOptions
* Adding instance_id to integration test and test file
changes listed here: https://github.com/IBM/scc-go-sdk/commit/d4b5fb2dfbe7f0a0250c7e56811b14d08740ace4
=> fix: Adding ProfileVersion to ReplaceProfileOptions

.github/workflows/main.yaml
Upgrade to node v20, replacing v18
=> ci: use node-version 20 rather than 18

.github/workflows/ci-check.yml, .github/workflows/ci_check.yaml, .github/workflows/main.yaml, README.md
=> ci: implemented a ci check

README.md
=> doc: fix the README

.github/workflows/ct-check.yml, .github/workflows/main.yaml, README.md
=> chore: fixing the naming for various files

v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3.go
Adds Madrid as a supported region(eu-es). 
Please make sure that your PR fulfills the following requirements:  
Current behavior does not allow you to target the region `eu-es`
=> fix: Add eu-es as a supported region

README.md, v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3.go
Changes:
- Changed the AdditionalTargetAttributes field `Value` from `string` to type `interface{}` #142
Added:
- Adding an example to the README.md
Please make sure that your PR fulfills the following requirements:  
Current Behavior:
```shell
Start main
{
"StatusCode": 200,
"Headers": {
"Cache-Control": [
"no-store"
],
"Cf-Cache-Status": [
"DYNAMIC"
],
"Cf-Ray": [
"880b038c5dcc2f75-LAX"
],
"Content-Type": [
"application/json; charset=utf-8"
],
"Date": [
"Wed, 08 May 2024 17:01:49 GMT"
],
"Etag": [
"W/\"8-7477f4840c6619850a6b787ac171f04a\""
],
"Server": [
"cloudflare"
],
"Strict-Transport-Security": [
"max-age=31536000; includeSubDomains"
],
"Transaction-Id": [
"b2419077-c619-41b1-adfb-bffd7ad25f39"
],
"X-Content-Type-Options": [
"nosniff"
],
"X-Correlation-Id": [ …
```
=> feat: Change AdditionalTargetAttributes.Value from string type to interface type

.gitignore, v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3.go, v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3_examples_test.go, v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3_integration_test.go, v5/securityandcompliancecenterapiv3/security_and_compliance_center_api_v3_test.go
Adding the feature to use the subrule operators `all`, `all_ifexists`, `any`, `any_ifexists`.
Closes #146
=> feat: Adding SubRule as a new feature

.github/workflows/main.yaml
=> ci: updating env vars

.releaserc
=> ci: updated releaserc with a URL

.github/workflows/main.yaml, .releaserc
=> ci: fixing the releaserc for release-semantics

v5/securityandcompliancecenterapiv3/security_and_compliance_center_v3.go, v5/securityandcompliancecenterapiv3/security_and_compliance_center_v3_examples_test.go, v5/securityandcompliancecenterapiv3/security_and_compliance_center_v3_integration_test.go, v5/securityandcompliancecenterapiv3/security_and_compliance_center_v3_test.go
Adds missing structs from the minor version bump
=> fix: added missing objects from Minor Update

v5/securityandcompliancecenterapiv3/security_and_compliance_center_v3.go
- Added a check to determine if the `Pager.Next.Start` are empty. If the string is empty, do not continue querying for data
=> fix: prevent infinite loop for ProfilesPager and ScopesPager
